version: 1.1.0{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2015
configuration:
- Release
platform: x64
clone_depth: 1
# C:\Qt\5.9 is mapped to C:\Qt\5.9.n for backward compatibility
install:
- cmd: >-
    choco install opencv
    
    cd thirdparty

    copy /Y LibJPEG\jpeg-9\jconfig.vc LibJPEG\jpeg-9\jconfig.h

    copy /Y tiff-4.0.3\libtiff\tif_config.vc.h tiff-4.0.3\libtiff\tif_config.h

    copy /Y tiff-4.0.3\libtiff\tiffconf.vc.h tiff-4.0.3\libtiff\tiffconf.h

    copy /Y libpng-1.6.21\scripts\pnglibconf.h.prebuilt libpng-1.6.21\pnglibconf.h


    cd ../toonz

    mkdir %PLATFORM% && cd %PLATFORM%

    cmake ..\sources -G "Visual Studio 14 2015 Win64" -DQT_PATH="C:\Qt\5.9\msvc2015_64" -DBOOST_ROOT="C:\Libraries\boost_1_60_0" -DOpenCV_DIR="C:\Tools\opencv\build"
build:
  project: $(APPVEYOR_BUILD_FOLDER)\toonz\$(PLATFORM)\ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    mkdir %CONFIGURATION%\Tahoma2D

    move %CONFIGURATION%\*.* %CONFIGURATION%\Tahoma2D

    C:\Qt\5.9\msvc2015_64\bin\windeployqt.exe %CONFIGURATION%\Tahoma2D\Tahoma2D.exe

    copy /Y ..\..\thirdparty\freeglut\bin\x64\freeglut.dll %CONFIGURATION%\Tahoma2D

    copy /Y ..\..\thirdparty\glew\glew-1.9.0\bin\64bit\glew32.dll %CONFIGURATION%\Tahoma2D

    copy /Y ..\..\thirdparty\libmypaint\dist\64\libiconv-2.dll %CONFIGURATION%\Tahoma2D

    copy /Y ..\..\thirdparty\libmypaint\dist\64\libintl-8.dll %CONFIGURATION%\Tahoma2D

    copy /Y ..\..\thirdparty\libmypaint\dist\64\libjson-c-2.dll %CONFIGURATION%\Tahoma2D
    
    copy /Y ..\..\thirdparty\libmypaint\dist\64\libmypaint-1-4-0.dll %CONFIGURATION%\Tahoma2D

    copy /Y ..\..\thirdparty\libjpeg-turbo64\dist\turbojpeg.dll %CONFIGURATION%\Tahoma2D

    copy /Y "C:\Tools\opencv\build\x64\vc14\bin\opencv_world451.dll" %CONFIGURATION%\Tahoma2D

    mkdir "%CONFIGURATION%\Tahoma2D\tahomastuff"

    xcopy /Y /E ..\..\stuff "%CONFIGURATION%\Tahoma2D\tahomastuff"
    
    curl -fsSL -o ffmpeg-4.3.1-win64-static-lgpl.zip https://github.com/tahoma2d/FFmpeg/releases/download/v4.3.1/ffmpeg-4.3.1-win64-static-lgpl.zip
    
    7z x ffmpeg-4.3.1-win64-static-lgpl.zip
    
    mkdir %CONFIGURATION%\Tahoma2D\ffmpeg

    copy /Y ffmpeg-4.3.1-win64-static-lgpl\bin\ffmpeg.exe %CONFIGURATION%\Tahoma2D\ffmpeg
    
    copy /Y ffmpeg-4.3.1-win64-static-lgpl\bin\ffprobe.exe %CONFIGURATION%\Tahoma2D\ffmpeg

    curl -fsSL -o rhubarb-lip-sync-tahoma2d-win.zip https://github.com/tahoma2d/rhubarb-lip-sync/releases/download/v1.10.2/rhubarb-lip-sync-tahoma2d-win.zip
    
    7z x rhubarb-lip-sync-tahoma2d-win.zip
    
    mkdir %CONFIGURATION%\Tahoma2D\rhubarb
    
    copy /Y rhubarb-lip-sync-tahoma2d-win\rhubarb.exe %CONFIGURATION%\Tahoma2D\rhubarb

    mkdir %CONFIGURATION%\Tahoma2D\rhubarb\res
    
    xcopy /Y /E rhubarb-lip-sync-tahoma2d-win\res "%CONFIGURATION%\Tahoma2D\rhubarb\res"

artifacts:
- path: toonz\$(PLATFORM)\$(CONFIGURATION)
  name: Tahoma2D
  
